### ISSUE TITLE
Boost loading time of BB

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/wishlist#27]
I recognized long loading times of BB on my demo/working system... Especially the Vuze-Cleaner seems to need a lot of time... I see it, if I start & log the loading of BB with the console EXE - BB seems to "hang" for some seconds when the Vuze-Cleaner gets checked ( - "VIM" is shown, because it's the last cleaner already loaded).
I guess this long loading time (check if the cleaner should be displayed) comes because the cleaner analyze the system (runs a "demo") (I guess so!)...
...and cleaners with a huge amount of files to analyze (file-sharing-cleaners, or e.g. a system-cleaner, if there are e.g a lot of temp-files) can need a lot of time for this...
So my suggestion is, to change this check in this way, that the cleaners don't make a complete "demo run", instead just run to the first file found, to know if they should be displayed.

**Comment by az0** [comment]
There are start-up improvements in version 2.1 like this. To determine whether to show a cleaner, the application is now more careful to find a single file rather than scanning many files. If it files a single file, it now stops without doing more work. If it finds no files, it has done little work. This process during application startup should take less than one second (probably much less) per cleaner. 

Cross-platform cleaners can be made a bit faster by adding the `os=` attribute in the XML. Version 2.1 adds support  for `os=` on the elements `action`, `value`, and `running`.

Later I'll check more into the Vuze case.

**Comment by Tobias-B-Besemer** [comment]
I guess the "Vuze Case" is because my v2.1 nightly still don't have the startup improvement... (?)
So you can save your time, if I do a new check with a version that have already the improvement.
Do latest Nighties already have the patch?

**Comment by az0** [comment]
Yes, the nightlies have the patch. It's been there since last year. Maybe there's something unique about the Vuze case

**Comment by Tobias-B-Besemer** [comment]
Vuze have the environment variables that don't work... But BiglyBT is a copy/fork and work... So I don't know!
Maybe it's VIM and not Vuze ???

**Comment by Tobias-B-Besemer** [comment]
Nope, sorry, it's Vuze! I renamed the cleaner and startup time was much faster...

**Comment by az0** [comment]
I am closing this because of fixes made and fixes in progress

See this issue "Vuze slow" regarding some improvements from  Paweł Polewicz. It seems to be the same issue as here.
https://github.com/bleachbit/bleachbit/issues/512

Another recent change a few weeks ago was changing the user interface to start before loading cleaners, so it shows a progress bar while working instead of showing nothing while loading cleaners.
