### ISSUE TITLE
explain when a cleaner is released to public rep

### ISSUE THREAD

**Issue by pas-calc** [bleachbit/wishlist#98]
There are a many different  repositories containing cleaners for bleachbit.

- One is  "bleachbit" with some [cleaners](https://github.com/bleachbit/bleachbit/tree/master/cleaners)
-  and "cleanerml" containing many cleaners , which in turn again categorized in [pending](https://github.com/bleachbit/cleanerml/tree/master/pending) & [release](https://github.com/bleachbit/cleanerml/tree/master/release)
- the official debian / ubuntu  ... [whatever repos](https://ubuntu.pkgs.org/20.10/ubuntu-universe-amd64/bleachbit_3.9.0-1_all.deb.html) , when are they updated?

What is the method of updating or releasing a version? I have seen the milestones using version numbers, but when a new version will be released and what cleaners will be included there? When will this be made public thru the official repos (Using apt / apt-get ) ?
Or is the option in the bleachbit menu to update automatically useful for this, what is going on there ("Check periodically for software updates via the Internet" / "Check for new beta releases") ?

**Comment by az0** [comment]
Cleaners for the most popular applications go into the bleachbit repository, and this is updated with each release of BleachBit (e.g., 4.0.0, 4.2.0).  The preference to check for updates will alert the user of a new release of the application, and then the user must manually download it.

Other CleanerML cleaners go in the cleanerml repository, and in an upcoming release, users will be able to access these through automatic online updates. Currently it's not easily accessible to average users. The distinction between pending and release has not been strongly maintained, and it may go away.

Ubuntu and Debian include the latest stable release of BleachBit when the Linux distribution is published, but they won't update it ever for that version of Ubuntu/Debian because of the "no rolling release" policy. It's sad to hear from Ubuntu users on LTS releases with ancient versions of BleachBit: users won't get an update until the next version of Ubuntu/Debian, so I recommend they download it from www.bleachbit.org instead. This is especially important for LTS releases.

On Windows, BleachBit users can check a preference to automatically download new versions of Winapp2.ini. This has its own Git repository too.

Does this help?

**Comment by pas-calc** [comment]
Thanks, that explained it very well.
